# Generated by Django 3.1.2 on 2020-11-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_fridgeproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='product',
        ),
    ]
