# Generated by Django 3.1.2 on 2021-01-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_auto_20210108_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='recpie',
            new_name='recipie',
        ),
    ]
