# Generated by Django 3.1.2 on 2021-01-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20210108_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='recipie',
            new_name='recipe',
        ),
    ]
