# Generated by Django 3.1.2 on 2020-11-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20201113_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
