# Generated by Django 3.1.5 on 2021-01-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_auto_20210110_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
    ]
