# Generated by Django 3.1.2 on 2021-01-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_auto_20210110_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeproduct',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fridgeproduct',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fridge.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
